import type { MetadataRoute } from "next";

/**
 * Web app manifest.
 *
 * Generated by Next.js at /manifest.webmanifest rather than written as a static
 * file, so the values stay in one place with the rest of the app metadata.
 *
 * This is what makes the site installable — "Add to Home Screen" on Android and
 * iOS — and it is also the prerequisite for the Play Store route. A Trusted Web
 * Activity is a thin Android wrapper around an installable PWA; Google rejects
 * wrappers that are only a WebView pointed at a website, so the manifest,
 * icons, offline behaviour and Digital Asset Links have to be real first.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Neighbour Trust",
    short_name: "Neighbour Trust",
    description:
      "Sourced, confidence-tagged neighbourhood data for Bengaluru, Gurugram, Hyderabad and Mumbai. " +
      "Every number says where it came from, how old it is, and how much to trust it.",

    start_url: "/",
    // `standalone` is what removes the browser chrome and makes an installed
    // copy read as an app. A TWA additionally requires it not be "browser".
    display: "standalone",
    orientation: "portrait",

    // The background shows during launch before the page paints, so it matches
    // the page's own surface rather than flashing white.
    background_color: "#fbfbfa",
    // Colours the Android status bar and the TWA splash. The brand pink, matching
    // viewport.themeColor in layout.tsx — they must agree or an installed copy
    // launches a different colour than the site it opens.
    theme_color: "#ff2d78",

    lang: "en-IN",
    dir: "ltr",
    categories: ["lifestyle", "utilities", "maps"],

    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      // Cropped by the launcher to the device's icon shape. Without a maskable
      // icon Android pads the plain one inside a white circle, which looks
      // broken next to every other app on the home screen.
      {
        src: "/icons/icon-maskable-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "maskable",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
